version: "3.9"

services:
  motivation-bot:
    build: .
    container_name: motivation-bot
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash ./start-all.sh  # запускаем через bash, чтобы избежать Permission denied
    restart: unless-stopped
